# Generated by Django 3.1.6 on 2021-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('post', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
            ],
        ),
    ]
